# Generated by Django 4.1.3 on 2022-11-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_image', models.CharField(max_length=100, null=True)),
                ('course_description', models.CharField(max_length=250)),
                ('course_duration', models.CharField(max_length=10)),
                ('course_fees', models.IntegerField(verbose_name=50)),
                ('course_content', models.CharField(max_length=150)),
                ('course_timing', models.TimeField(max_length=10, null=True)),
                ('course_level', models.CharField(max_length=50)),
                ('course_language', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('expert_id', models.AutoField(primary_key=True, serialize=False)),
                ('expert_name', models.CharField(max_length=50)),
                ('expert_email', models.EmailField(max_length=150)),
                ('expert_contact', models.CharField(max_length=13)),
                ('expert_image', models.CharField(max_length=100, null=True)),
                ('expert_password', models.CharField(max_length=100)),
                ('expert_qualification', models.CharField(max_length=15)),
                ('expert_experience', models.CharField(max_length=15)),
                ('registered_date', models.DateField(null=True)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(null=True, verbose_name=10)),
            ],
            options={
                'db_table': 'Expert',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.AutoField(primary_key=True, serialize=False)),
                ('stream_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Stream',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_password', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=150)),
                ('student_contact', models.CharField(max_length=13)),
                ('registered_date', models.DateField()),
                ('is_admin', models.IntegerField(null=True)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(null=True, verbose_name=10)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('stream_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.stream')),
            ],
            options={
                'db_table': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Subject_Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50)),
                ('uploaded_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=250)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.course', verbose_name='Course')),
            ],
            options={
                'db_table': 'Subject_Material',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_description', models.CharField(max_length=250)),
                ('query_response', models.CharField(max_length=250, null=True)),
                ('query_date', models.DateField()),
                ('solve_date', models.DateField()),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.course', verbose_name='Course')),
                ('expert_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.expert', verbose_name='Expert')),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.students', verbose_name='Students')),
            ],
            options={
                'db_table': 'Query',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_description', models.CharField(max_length=250)),
                ('feedback_date', models.DateField()),
                ('rate', models.IntegerField(verbose_name=5)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.course')),
                ('expert_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.expert', verbose_name='Expert')),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.students', verbose_name='Students')),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Course_booking',
            fields=[
                ('course_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField(null=True)),
                ('booking_status', models.IntegerField(verbose_name=10)),
                ('booking_description', models.CharField(max_length=250)),
                ('amount', models.IntegerField(null=True)),
                ('payment_status', models.IntegerField(verbose_name=10)),
                ('charges', models.IntegerField(verbose_name=50)),
                ('total_amount', models.IntegerField(verbose_name=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.students')),
            ],
            options={
                'db_table': ' Course_booking',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='expert_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.expert', verbose_name='Expert'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.subjects'),
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField(max_length=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.students')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
